export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/categories/icons8-pizza-96.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/categories/icons8-hamburger-96.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/categories/icons8-spaghetti-96.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/categories/icons8-takeout-box-96.png"),
  },
  {
    id: 5,
    name: "Cupcake",
    image: require("../assets/categories/icons8-cupcake-emoji-96.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/categories/icons8-tropical-drink-96.png"),
  },
];

export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and  tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Delicous",
      image: require("../assets/restaurants/n7yx-hero (1).jpg"),
      description: "Hot and Spicy KFC",
      lng: 38.2145602,
      lat: -85.5324269,
      adress: "434 second street",
      start: 4,
      review: "4.4k",
      categories: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Mini Pizza",
          description: "Cheezy garlic pizza",
          price: 1000,
          image: require("../assets/dishes/download (1) (1).jpeg"),
        },
        {
          id: 2,
          name: "Mini Pizza",
          description: "Craipe sucrer",
          price: 1000,
          image: require("../assets/dishes/download (2) (1).jpeg"),
        },
        {
          id: 3,
          name: "Mini KFC",
          description: "Cheezy garlic KFC",
          price: 1500,
          image: require("../assets/dishes/download (2) (2).jpeg"),
        },
        {
          id: 4,
          name: "Soupe",
          description: "Soupe Concentre",
          price: 2000,
          image: require("../assets/dishes/download (2) (3).jpeg"),
        },
      ],
    },
    {
      id: 2,
      name: "Yacine",
      image: require("../assets/restaurants/disadvantages-of-fast-food (1).webp"),
      description: "Hot and Spicy KFC",
      lng: 38.2145602,
      lat: -85.5324269,
      adress: "434 second street",
      start: 5,
      review: "4.4k",
      categories: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pastel",
          description: "Pastel Avec laitue",
          price: 1000,
          image: require("../assets/dishes/download (3) (1).jpeg"),
        },
        {
          id: 2,
          name: "Pancake",
          description: "Hot Pancake",
          price: 1500,
          image: require("../assets/dishes/download (3) (2).jpeg"),
        },
        {
          id: 3,
          name: "Pasta",
          description: "Pasta sauce",
          price: 1500,
          image: require("../assets/dishes/download (3) (3).jpeg"),
        },
        {
          id: 4,
          name: "Fire Fish",
          description: "Hot sea Fish",
          price: 1000,
          image: require("../assets/dishes/download (4) (1).jpeg"),
        },
      ],
    },
    {
      id: 3,
      name: "Papa Jones",
      image: require("../assets/restaurants/n7yx-hero (1).jpg"),
      description: "Hot and Spicy KFC",
      lng: 38.2145602,
      lat: -85.5324269,
      adress: "434 second street",
      start: 4,
      review: "4.4k",
      categories: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Friture",
          description: "Hot frite withe egg",
          price: 3000,
          image: require("../assets/dishes/download (5) (1).jpeg"),
        },
        {
          id: 2,
          name: "Jump Rice",
          description: "Rice with egg",
          price: 2000,
          image: require("../assets/dishes/download (6) (1).jpeg"),
        },
        {
          id: 3,
          name: "Mallo",
          description: "some Mallo kini",
          price: 1000,
          image: require("../assets/dishes/download (8).jpeg"),
        },
        {
          id: 1,
          name: "Brochette",
          description: "Brochette chaude ",
          price: 200,
          image: require("../assets/dishes/download (9).jpeg"),
        },
      ],
    },
  ],
};
